# Generated by Django 3.1.5 on 2021-01-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='realname',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='teacher_type',
            field=models.CharField(max_length=255, verbose_name='身分'),
        ),
    ]
