# Generated by Django 3.1.5 on 2021-01-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200211_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='preface',
            field=models.ImageField(upload_to='', verbose_name='圖片'),
        ),
    ]
